# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'ContactApp' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Swinject'
end
